image: cypress/included:3.2.0

before_script:
  - npm install

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}

cypress:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - /cypress/videos/
