image: cypress/include

before_script:
  - npm install

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

cypress:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - /cypress/videos/
